In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

df = pd.read_csv('car_data.csv')
df.describe()
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage(km/ltr/kg)', 'engine'],
      dtype='str')

In [4]:
car_models = df['name'].to_list()

brands = [car_model.split()[0] for car_model in car_models]

df.insert(0,'brand',brands)

y = df['selling_price']
x = df.drop(columns=['name','selling_price'])

x = pd.get_dummies(x, columns=['brand','fuel','seller_type','transmission','owner'], drop_first=True)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

model = RandomForestRegressor()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_pred, y_test)
rmse = np.sqrt(mse)

print(rmse)
#print(y_train.to_string())

161974.63769043863

In [6]:
from sklearn.metrics import r2_score
train_r2 = r2_score(y_train, model.predict(x_train))
test_r2 = r2_score(y_test, model.predict(x_test))
print(train_r2)
print(test_r2)

0.9924411183476444
0.9557196264256256

In [7]:
import pandas as pd

# Check what the model is actually relying on
if hasattr(model, "feature_importances_"):
    feat_imp = pd.Series(model.feature_importances_, index=x_train.columns)
    print("--- Top 5 Features Driving This 0.96 Score ---")
    print(feat_imp.sort_values(ascending=False).head(5))

--- Top 5 Features Driving This 0.96 Score ---
transmission_Manual    0.354669
engine                 0.299096
year                   0.247932
mileage(km/ltr/kg)     0.030030
km_driven              0.026817
dtype: float64

In [8]:
rmse

np.float64(161974.63769043863)

In [9]:
mse

26235783254.94886

In [10]:
df.describe()

,year,selling_price,km_driven,mileage(km/ltr/kg),engine
count,8128.000000,8.128000e+03,8.128000e+03,7907.000000,7907.000000
mean,2013.804011,6.382718e+05,6.981951e+04,19.418783,1458.625016
std,4.044249,8.062534e+05,5.655055e+04,4.037145,503.916303
min,1983.000000,2.999900e+04,1.000000e+00,0.000000,624.000000
25%,2011.000000,2.549990e+05,3.500000e+04,16.780000,1197.000000
50%,2015.000000,4.500000e+05,6.000000e+04,19.300000,1248.000000
75%,2017.000000,6.750000e+05,9.800000e+04,22.320000,1582.000000
max,2020.000000,1.000000e+07,2.360457e+06,42.000000,3604.000000

In [11]:
prediction = model.predict([[2004,110000,12.80,1493.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1]])
print(y_test.iloc[0])
print(prediction)

210000
[190660.]

/opt/anaconda3/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [12]:
import joblib

joblib.dump(model, 'car_price_model.pkl')
joblib.dump(list(x_train.columns), 'car_columns.pkl')

print('Successful')

Successful

In [13]:
x_train.tail()

,year,km_driven,mileage(km/ltr/kg),engine,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6855,2018,19700,18.15,1198.0,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False
902,2011,90000,20.00,1399.0,False,False,False,False,False,False,...,True,False,False,True,False,True,False,True,False,False
3769,2017,28000,27.39,1248.0,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False
2082,2010,110000,17.00,1405.0,False,False,False,False,False,False,...,True,False,False,True,False,True,False,True,False,False
1911,2014,60000,19.00,998.0,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False

In [17]:
x_train.columns

Index(['year', 'km_driven', 'mileage(km/ltr/kg)', 'engine', 'brand_Ashok',
       'brand_Audi', 'brand_BMW', 'brand_Chevrolet', 'brand_Daewoo',
       'brand_Datsun', 'brand_Fiat', 'brand_Force', 'brand_Ford',
       'brand_Honda', 'brand_Hyundai', 'brand_Isuzu', 'brand_Jaguar',
       'brand_Jeep', 'brand_Kia', 'brand_Land', 'brand_Lexus', 'brand_MG',
       'brand_Mahindra', 'brand_Maruti', 'brand_Mercedes-Benz',
       'brand_Mitsubishi', 'brand_Nissan', 'brand_Opel', 'brand_Peugeot',
       'brand_Renault', 'brand_Skoda', 'brand_Tata', 'brand_Toyota',
       'brand_Volkswagen', 'brand_Volvo', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol', 'seller_type_Individual', 'seller_type_Trustmark Dealer',
       'transmission_Manual', 'owner_Fourth & Above Owner',
       'owner_Second Owner', 'owner_Test Drive Car', 'owner_Third Owner'],
      dtype='str')